### ISSUE TITLE
Implement MedianXL/save folder initiation to prevent "Generic bad character"

### ISSUE THREAD

**Issue by roalyr** [murkl/d2launcher#9]
Directory must be initiated after making a wineprefix:
`.wineprefix/drive_c/users/steamuser/AppData/Roaming/MedianXL/save`

This will prevent "Generic bad character" error when creating a new character.

**Comment by murkl** [comment]
Thanks for reporting this. I will fix this in the next release!

**Comment by murkl** [comment]
Is fixed in new release 3.5.3
